### ISSUE TITLE
Move website to use Documenter.jl

### ISSUE THREAD

**Issue by giordano** [JuliaAstro/JuliaAstro.github.io#11]
The current website is completely in HTML and not particularly fun to edit. I'd much prefer to move to use something like Documenter.jl, like what we did for JuliaPhysics website: https://github.com/JuliaPhysics/juliaphysics.github.io

The layout will probably need to change (the current tables are probably not easy to reproduce with Documenter.jl), but I think that the easy of use is worth the change.

**Comment by mileslucas** [comment]
I’d be happy to take a look at this. I think a documenter based website with some custom css could yield a nice mix between easy to maintain but unique and usable.

**Comment by mileslucas** [comment]
although there’s something to be said that a simple static site might be better done in JavaScript. A vue based site could easily abstract away some of the nitty gritty and allow easy changes (something like a vue element for  packages in the ecosystem) but is much more expressive than documenters markdown heavy approach.

We could find an uncanny medium, too, with something like vuepress that can use markdown for blog post style code entries but is based in vue and has all the functionality available through that.

**Comment by giordano** [comment]
I don't feel particularly attached to the current layout, so changing it is completely fine with me. I think the CI badges can be completely removed, the important thing is to keep the list of the packages, with short descriptions and links to the repositories and docs. Also the community section is important.

I don't think javascript is a great improvement compared to HTML in terms of maintainability. I'm not a web developer and I don't think many of us are, I really like the heavily markdown-based approach of Documenter.jl, as the contribution barrier is very low.

**Comment by mileslucas** [comment]
I definitely agree- documenter has the lowest barrier to entry for a julia programmer. I will happily whip up a documenter version and possibly (depends on class load over the next week or so) a comparable vuepress based site (which is also primarily written in markdown).

**Comment by giordano** [comment]
Awesome, thanks!

**Comment by mileslucas** [comment]
@giordano Here's my first stab at documenter 
http://docs-temp-dustextinction.s3-website-us-west-1.amazonaws.com/index.html
the source is inter-spersed with the original on [my fork](https://github.com/mileslucas/JuliaAstro.github.io/tree/documenter)

**Comment by giordano** [comment]
I'm curious to see your other option (no rush! And no problem if you can't make it), but for me this is already just perfect: simple, effective, and easy to contribute to 🙂

**Comment by mileslucas** [comment]
@giordano here is my vuepress first stab. I recommend taking a look at the [homepage markdown file](https://github.com/mileslucas/JuliaAstro.github.io/blob/vuepress/src/README.md) to see how it is also a nice mix of customizable but simple. Anybody who wants to add a project or a documentation link can do so very easily, but any higher level customization and re-organiation would require knowledge of vue (to an extent, I wouldn't consider myself as someone who knows vue but I got this built).

http://docs-temp-juliaastro.s3-website-us-west-1.amazonaws.com/

**Comment by mileslucas** [comment]
Close via #12
